### ISSUE TITLE
Its not working on Gnome 3.10

### ISSUE THREAD

**Issue by rajeshksv** [bndn/gedit-sessionsaver#1]
Looks like this extension is not working in Gnome 3.10(Ubuntu 13.10 , gnome shell 3.10). I enabled the extension , opened two tabs, closed Gedit, opened it again and  couldn't see those two tabs open automatically on startup. 

I tried both python 2 and python 3 versions of this plugin (Both python 2 and python 3 are installed on my system)
I couldn't even enable Python2 version in plugins section. I was able to enable python3 version of the plugin but I am not able to restore tabs on startup

**Comment by bndn** [comment]
The plugin doesn’t work like this. When it’s enabled, you have to create a session with the File > Saved session > Save current session button. It should works on your system with the python3 version.
(If you need, I updated the repo to fix some little bugs)

**Comment by rajeshksv** [comment]
Ok. Thanks. Got it

But it would be better, if we can automatically save session instead of manually saving.

**Comment by bndn** [comment]
I agree. I’ll try to work to improve it. Thanks for the proposal.

**Comment by francesquini** [comment]
Using:
Ubuntu: 13.10
Gedit: 3.8.3
Python: 3.3.2 (package python3-gi installed)
Session Saver: 3.6.1 (Actually, git commit 32418e5239560464f2b7ddb07e1a410e276ed3d2)

Followed the install instructions as stated here: https://github.com/sphax3d/gedit-sessionsaver/blob/master/README.md

Save current session does not restore open files upon reopening Gedit. This happens even if I click "Save current session" immediately before quiting Gedit. Moreover, clicking on the "Manage saved sessions..." menu item apparently has no effect. 

Any clues?

**Comment by dhjw** [comment]
francesquini, check issues #2 & #3

**Comment by WoodyGrape** [comment]
Hhmm this is not working for me on Fedora 20, with Gedit 3.10.3.

I install it, activate it, but when i click save current session, nothing happens.

On Fedora 18 with the previous gedit, When clicking save session you type in the name and save.

Seems broken with the new gedit.  Any ideas?

**Comment by dhjw** [comment]
Try applying patch #3 manually, as it has not yet been merged with the main branch.  If that doesn't work run gedit from a terminal so you can see error messages when you click "Save current session" and "Manage saved sessions" and start a new issue with full details.

**Comment by WoodyGrape** [comment]
Ok I got it, Added patch #3 manually, but still wasn't working.  Since all my plugins were in /usr/lib64/gedit/plugins, that's where I copied sessionsaver.  Then I was getting the error:

gi._glib.GError: Failed to open file '/usr/share/gedit/plugins/sessionsaver/sessionsaver.ui': No such file or directory

Copied the sessionsaver.ui to that directory and all is good.  THANK YOU!
