### ISSUE TITLE
Broken in Ubuntu 13.10?

### ISSUE THREAD

**Issue by dhjw** [bndn/gedit-sessionsaver#2]
I'm getting errors on ubuntu 13.10 / gedit 3.8.3 / python3:

Running from terminal, on Save, I get this:

Traceback (most recent call last):
File "/home/user/.local/share/gedit/plugins/sessionsaver/init.py", line 161, in on_save_session_action
SaveSessionDialog(self.window, self, self.sessions).run()
TypeError: new() takes 1 positional argument but 4 were given

On Manage, I get this:

Traceback (most recent call last):
File "/home/user/.local/share/gedit/plugins/sessionsaver/init.py", line 164, in on_manage_sessions_action
SessionManagerDialog(self, self.sessions).run()
TypeError: new() takes 1 positional argument but 3 were given

...and with both, nothing ever happens in gedit.

Thanks for any advice or fix.

**Comment by amandabee** [comment]
I'm not seeing any errors (maybe not looking in the right place?) but nothing happens when I select "file > saved sessions > save current session"

**Comment by careca1970** [comment]
Useful plugin, but...
Same behavior as dhjw, on:
gedit - Version 3.8.3   |   Python 3.3.2   |   gnome 3.8.4   |   Fedora 19
Please, help. Thanks!

**Comment by olehlong** [comment]
I have fixed it (maybe wrong, but it works): 
in dialogs.py (line 54):
def **new**(cls):
replace with:
def **new**(cls, *args):

Without it gedit 3.10.4 gives an error:
plugins/sessionsaver/**init**.py", line 164, in on_manage_sessions_action
    SessionManagerDialog(self, self.sessions).run()
TypeError: **new**() takes 1 positional argument but 3 were given

**Comment by careca1970** [comment]
Change proposed by gaolong works. Thank you!
Will it be updated in the project?

**Comment by dhjw** [comment]
Awesome, thanks!  I submitted a request to merge.

**Comment by bumbar1** [comment]
Seems the fix was not merged? [link](https://github.com/sphax3d/gedit-sessionsaver/blob/master/sessionsaver/dialogs.py#L54)

Sorry to comment on closed issue, but I really love this plugin!

**Comment by dhjw** [comment]
The Pull Request (#3) is still open - sphax3d hasn't approved it yet.  You'll have to manually apply the fix or grab the copy from my repository.

**Comment by rajeshksv** [comment]
The fix is working . Thanks :) Very useful plugin!

**Comment by bezdelnique** [comment]
Thank's to @olehlong ! :)
